import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service  TOOLBeans',
  description: 'Read the TOOLBeans Terms of Service before using our free developer tools.',
};

const sections = [
  {
    icon: '📜',
    title: 'Acceptance of Terms',
    content: [
      'By accessing and using TOOLBeans ("the Platform"), you agree to be bound by these Terms of Service and all applicable laws and regulations.',
      'If you do not agree with any of these terms, you are prohibited from using or accessing TOOLBeans. Please discontinue use immediately if you do not accept these terms.',
    ],
    bullets: [],
  },
  {
    icon: '🛠️',
    title: 'Description of Service',
    content: [
      'TOOLBeans provides free, browser-based developer utility tools including but not limited to: password generators, QR code generators, text case converters, Base64 encoders/decoders, URL encoders/decoders, JSON formatters, and SQL formatters.',
      'All tools are provided "as is" without warranty of any kind, express or implied. We reserve the right to modify, suspend, or discontinue any tool at any time without notice.',
    ],
    bullets: [],
  },
  {
    icon: '✅',
    title: 'Acceptable Use',
    content: [
      'You agree to use TOOLBeans only for lawful purposes and in a way that does not infringe the rights of others. The following uses are strictly prohibited:',
    ],
    bullets: [
      'Using TOOLBeans for any illegal or unauthorized purpose',
      'Attempting to reverse-engineer, hack, or disrupt the Platform',
      'Automated scraping or excessive automated requests',
      'Generating content that violates third-party intellectual property rights',
      'Uploading or transmitting viruses or malicious code',
      'Impersonating any person, company, or entity',
    ],
  },
  {
    icon: '©️',
    title: 'Intellectual Property',
    content: [
      'All content, design, branding, and source code on TOOLBeans is the property of TOOLBeans and its licensors and is protected by applicable intellectual property laws.',
      'The output generated by our tools  passwords, formatted code, QR codes, encoded strings  belongs entirely to you. We claim no ownership over content you create using our tools.',
    ],
    bullets: [],
  },
  {
    icon: '⚠️',
    title: 'Disclaimer of Warranties',
    content: [
      'TOOLBeans tools are provided for convenience and productivity purposes. We make no guarantees regarding accuracy, completeness, security, or fitness for a particular purpose.',
      'Always verify critical outputs independently. For example, generated passwords should be tested against your specific security requirements before use in production systems.',
    ],
    bullets: [],
  },
  {
    icon: '🛡️',
    title: 'Limitation of Liability',
    content: [
      'To the maximum extent permitted by applicable law, TOOLBeans shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Platform.',
      'This includes but is not limited to: loss of data, loss of profits, or any damages resulting from reliance on tool outputs.',
    ],
    bullets: [],
  },
  {
    icon: '🔗',
    title: 'Third-Party Links',
    content: [
      'TOOLBeans may contain links to third-party websites or services that are not owned or controlled by us. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites.',
      'We strongly recommend reading the terms and privacy policies of any third-party sites you visit.',
    ],
    bullets: [],
  },
  {
    icon: '📢',
    title: 'Advertisements',
    content: [
      'TOOLBeans displays third-party advertisements to fund the free availability of our tools. By using TOOLBeans, you agree to the display of these advertisements.',
      'We are not responsible for the content of third-party advertisements. Any interactions with advertisers are solely between you and the advertiser.',
    ],
    bullets: [],
  },
  {
    icon: '🔄',
    title: 'Changes to Terms',
    content: [
      'We reserve the right to modify these Terms of Service at any time. Changes will be effective immediately upon posting to the Platform.',
      'Continued use of TOOLBeans after any changes constitutes your acceptance of the new Terms of Service. We recommend reviewing these terms periodically.',
    ],
    bullets: [],
  },
  {
    icon: '⚖️',
    title: 'Governing Law',
    content: [
      'These Terms of Service shall be governed by and construed in accordance with applicable laws, without regard to conflict of law provisions.',
      'Any disputes arising from these terms or your use of TOOLBeans shall be resolved through good-faith negotiation before pursuing any other remedy.',
    ],
    bullets: [],
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen">

      {/* ── HERO ── */}
      <section className="bg-gradient-to-br from-indigo-50 via-white to-cyan-50 border-b border-slate-100 py-16">
        <div className="max-w-4xl mx-auto px-6 text-center">
          <span className="inline-block bg-indigo-50 text-indigo-600 text-xs font-bold uppercase tracking-widest px-3 py-1 rounded-full mb-4">
            Legal
          </span>
          <h1 className="text-4xl md:text-5xl font-extrabold text-slate-900 mb-4">
            Terms of{' '}
            <span className="bg-gradient-to-r from-indigo-600 to-cyan-500 bg-clip-text text-transparent">
              Service
            </span>
          </h1>
          <p className="text-sm text-slate-500 font-light max-w-xl mx-auto mb-6">
            Please read these terms carefully before using TOOLBeans. By using our platform,
            you agree to be bound by these terms.
          </p>
          {/* Last Updated Badge */}
          <div className="inline-flex items-center gap-2 bg-white border border-slate-200 rounded-full px-4 py-2 text-xs text-slate-500 shadow-sm">
            <span className="w-1.5 h-1.5 bg-green-400 rounded-full" />
            Last Updated: January 2025
          </div>
        </div>
      </section>

      {/* ── QUICK SUMMARY ── */}
      <section className="max-w-5xl mx-auto px-6 py-12">
        <div className="bg-amber-50 border border-amber-200 rounded-2xl p-6">
          <div className="flex items-start gap-4">
            <div className="text-3xl flex-shrink-0">💡</div>
            <div>
              <h3 className="font-extrabold text-amber-900 text-sm mb-2">
                Plain English Summary
              </h3>
              <p className="text-xs text-amber-800 leading-relaxed mb-3">
                Here&apos;s a quick, simple summary of our Terms. The full legal text is below.
              </p>
              <ul className="space-y-1.5">
                {[
                  'Use our tools freely  they are 100% free and always will be',
                  'Don\'t misuse the platform for illegal or harmful activities',
                  'Tool outputs (passwords, formatted code, etc.) belong to you',
                  'We are not liable if a tool output causes issues  always verify critical results',
                  'We may show ads to keep the platform free for everyone',
                  'These terms can change  we\'ll always show the updated date',
                ].map((item, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-amber-800">
                    <span className="text-amber-500 flex-shrink-0 mt-0.5">✓</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* ── TERMS SECTIONS ── */}
      <section className="max-w-4xl mx-auto px-6 pb-20">
        <div className="flex flex-col gap-5">
          {sections.map((sec, i) => (
            <div
              key={i}
              className="bg-white border border-slate-200 rounded-2xl p-7 shadow-sm hover:shadow-md transition-shadow duration-200"
            >
              {/* Header */}
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 bg-indigo-50 rounded-xl flex items-center justify-center text-xl flex-shrink-0">
                  {sec.icon}
                </div>
                <h2 className="text-lg font-extrabold text-slate-900">
                  {i + 1}. {sec.title}
                </h2>
              </div>

              {/* Content */}
              <div className="space-y-3">
                {sec.content.map((para, j) => (
                  <p key={j} className="text-sm text-slate-500 leading-relaxed font-light">
                    {para}
                  </p>
                ))}

                {/* Bullets */}
                {sec.bullets.length > 0 && (
                  <ul className="mt-3 space-y-2 bg-slate-50 rounded-xl p-4">
                    {sec.bullets.map((b, k) => (
                      <li key={k} className="flex items-start gap-2 text-sm text-slate-500">
                        <span className="text-rose-400 mt-0.5 flex-shrink-0">✕</span>
                        {b}
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            </div>
          ))}
        </div>

        {/* ── AGREEMENT BOX ── */}
        <div className="mt-8 bg-gradient-to-br from-indigo-600 to-violet-600 rounded-2xl p-8 text-center text-white">
          <div className="text-3xl mb-3">🤝</div>
          <h3 className="text-lg font-extrabold mb-2">
            By Using TOOLBeans, You Agree to These Terms
          </h3>
          <p className="text-indigo-100 text-xs font-light mb-6 max-w-md mx-auto">
            If you have any questions about these Terms of Service, please contact us
            before using the platform. We&apos;re happy to clarify anything.
          </p>
          <Link
            href="/contact"
            className="inline-flex items-center gap-2 bg-white text-indigo-600 font-bold px-6 py-3 rounded-xl hover:-translate-y-0.5 hover:shadow-xl transition-all duration-200 text-sm"
          >
            💬 Ask a Question
          </Link>
        </div>

        {/* ── RELATED LINKS ── */}
        <div className="mt-6 flex flex-wrap gap-3 justify-center">
          <Link
            href="/privacy"
            className="text-sm text-indigo-600 bg-indigo-50 hover:bg-indigo-100 font-semibold px-4 py-2 rounded-xl transition-colors"
          >
            Privacy Policy →
          </Link>
          <Link
            href="/contact"
            className="text-sm text-slate-600 bg-slate-100 hover:bg-slate-200 font-semibold px-4 py-2 rounded-xl transition-colors"
          >
            Contact Page →
          </Link>
          <Link
            href="/tools"
            className="text-sm text-slate-600 bg-slate-100 hover:bg-slate-200 font-semibold px-4 py-2 rounded-xl transition-colors"
          >
            Browse Tools →
          </Link>
        </div>
      </section>

    </div>
  );
}